# Generated by Django 6.0.3 on 2026-03-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
